version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    hostname: redis
    networks:
      - backend
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  ecommerce_scraper_api:
    build: ./ecommerce-scraper-api
    ports:
      - 8000:8000
    container_name: ecommerce-scraper-api
    depends_on:
      - redis
    environment:
      REDIS_SERVER: redis://redis:6379
    networks:
      - backend
    volumes:
      - redis_data:/data
    restart: always

  react_frontend:
    depends_on: 
      - ecommerce_scraper_api
    build: ./react-frontend
    ports:
      - 3000:3000
    container_name: react-frontend
    environment:
      - REACT_APP_BACKEND_API=http://localhost:8000


networks:
  backend:

volumes:
  redis_data:
    driver: local
